xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    Flow_m3_sec_zscore_norm:
      dims: []
      attrs: {}
      data: 0.6673508286476135
    Flow_m3_sec_zscore_norm_shift18:
      dims: []
      attrs: {}
      data: 0.6673333644866943
    Rain_gauge_1_zscore_norm:
      dims: []
      attrs: {}
      data: 0.9140492081642151
    Rain_gauge_2_zscore_norm:
      dims: []
      attrs: {}
      data: 0.9776628613471985
    Rain_gauge_3_zscore_norm:
      dims: []
      attrs: {}
      data: 0.9799903631210327
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    Flow_m3_sec_zscore_norm:
      dims: []
      attrs: {}
      data: -0.017976578325033188
    Flow_m3_sec_zscore_norm_shift18:
      dims: []
      attrs: {}
      data: -0.018053637817502022
    Rain_gauge_1_zscore_norm:
      dims: []
      attrs: {}
      data: -3.6383746191859245e-05
    Rain_gauge_2_zscore_norm:
      dims: []
      attrs: {}
      data: 0.0005309191765263677
    Rain_gauge_3_zscore_norm:
      dims: []
      attrs: {}
      data: 0.001087360200472176
