autoregressive_inputs:
- unit_discharge_m3_sec_km_shift18
dynamic_inputs:
- Rain_gauge_1_zscore_norm
- Rain_gauge_2_zscore_norm
- Rain_gauge_3_zscore_norm
batch_size: 2048
clip_gradient_norm: 1
clip_targets_to_zero:
- unit_discharge_m3_sec_km
data_dir: ..\..\..\..\data\Caravan
dataset: caravan
device: cpu
epochs: 15
experiment_name: hidden_size64_seq_length36_learning_rate0001_unit_discharge_training_zscore_norm_rain
forcings:
- il
head: regression
hidden_size: 64
initial_forget_bias: 3
lagged_features:
  Rain_gauge_1_zscore_norm:
  - 18
  Rain_gauge_2_zscore_norm:
  - 18
  Rain_gauge_3_zscore_norm:
  - 18
  unit_discharge_m3_sec_km:
  - 18
learning_rate: 0.001
log_interval: 5
log_n_figures: 8
log_tensorboard: true
loss: MSE
metrics:
- NSE
model: arlstm
num_workers: 0
optimizer: Adam
output_activation: linear
output_dropout: 0.4
predict_last_n: 1
save_weights_every: 1
seq_length: 36
target_variables:
- unit_discharge_m3_sec_km
test_basin_file: LSTM_shared_8basins.txt
test_end_date: 28/05/2018
test_start_date: 01/10/2017
train_basin_file: LSTM_shared_8basins.txt
train_end_date:
- 30/05/2011
- 30/05/2012
- 30/05/2013
- 30/05/2014
- 30/05/2015
train_start_date:
- 07/10/2010
- 07/10/2011
- 07/10/2012
- 07/10/2013
- 07/10/2014
validate_every: 1
validate_n_random_basins: 0
validation_basin_file: LSTM_shared_8basins.txt
validation_end_date: 30/05/2017
validation_start_date: 01/10/2015

use_basin_id_encoding: false

