autoregressive_inputs:
- Flow_m3_sec_zscore_norm_shift18
batch_size: 512
clip_gradient_norm: 1
# clip_targets_to_zero:
# - Flow_m3_sec_zscore_norm
# data_dir: ..\..\..\..\..\..\data\Caravan
data_dir: C:\PhD\Data\Caravan
# data_dir: /sci/labs/efratmorin/omripo/PhD/Data/Caravan/
dataset: caravan
device: cpu
# device: cuda:0
dynamic_inputs:
- Rain_gauge_1_zscore_norm
- Rain_gauge_2_zscore_norm
- Rain_gauge_3_zscore_norm
epochs: 5
experiment_name: Best_HPC_training_zscore_norm_hidden_size256_batch_size512_learning_rate0001
forcings:
- il
head: regression
hidden_size: 256
initial_forget_bias: 3
lagged_features:
  Flow_m3_sec_zscore_norm:
  - 18
  Rain_gauge_1_zscore_norm:
  - 18
  Rain_gauge_2_zscore_norm:
  - 18
  Rain_gauge_3_zscore_norm:
  - 18
learning_rate: 0.001
log_interval: 5
log_n_figures: 8
log_tensorboard: true
loss: MSE
metrics:
- NSE
model: arlstm
num_workers: 0
optimizer: Adam
output_activation: linear
output_dropout: 0.4
predict_last_n: 1
save_weights_every: 1
seq_length: 36
target_variables:
- Flow_m3_sec_zscore_norm
test_basin_file: C:\PhD\Python\NH-shared-flow-rain\nhWrap\neuralhydrology\LSTM_shared_RainDis2Dis\Apply_metrics_to_train_and_validation\LSTM_shared_8basins.txt
test_end_date: 28/05/2018
test_start_date: 01/10/2017
train_basin_file: C:\PhD\Python\NH-shared-flow-rain\nhWrap\neuralhydrology\LSTM_shared_RainDis2Dis\Apply_metrics_to_train_and_validation\LSTM_shared_8basins.txt
train_end_date:
- 30/09/2015
train_start_date:
- 01/10/2010
use_basin_id_encoding: false
validate_every: 1
validate_n_random_basins: 8
validation_basin_file: C:\PhD\Python\NH-shared-flow-rain\nhWrap\neuralhydrology\LSTM_shared_RainDis2Dis\Apply_metrics_to_train_and_validation\LSTM_shared_8basins.txt
validation_end_date: 30/09/2017
validation_start_date: 01/10/2015
